swagger: "2.0"
info:
  description: "We are going to get the role of employee"
  version: "1.0.0"
  title: "Role Base"
  contact:
    email: "Ali.Satti@wanclouds.net"
host: "ems.swagger.io"
basePath: "/v1"
schemes:
  - "http"
paths:
  /role/{designation}/{apiName}:
    get:
      tags:
        - "Getting Role"
      summary: "get roles"
      operationId: "getrole"
      produces:
        - "application/json"
      parameters:
        - in: path
          name: designation
          type: string
          required: true
          description: Enter desination.
        - in: path
          name: apiName
          type: string
          required: true
          description: Enter apiName.
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/rolereturn"
        500:
          description: Internal server error
          schema:
            $ref: "#/definitions/rolereturn1"
        403:
          description: Forbidden
          schema:
            $ref: "#/definitions/rolereturn2"
        400:
          description: Bad request
          schema:
            $ref: "#/definitions/rolereturn3"
definitions:
  rolereturn:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
  rolereturn1:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
  rolereturn2:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
  rolereturn3:
    type: object
    properties:
      code:
        type: integer
      message:
        type: string
